name: "Android: Build"
description: "Builds Android APK using Flutter with explicit flavor and mode."

inputs:
  flavor:
    description: "Build flavor (e.g., development, staging, production)."
    required: true
  mode:
    description: "Build mode (debug, profile, release)."
    default: "release"
    required: false
  target:
    description:
      "Path to the target main file (e.g., lib/main_development.dart)."
    required: true
  version-tag:
    description: "Version tag or identifier to append to the filename."
    required: true

outputs:
  apk-path:
    description: "Path to the final renamed APK file."
    value: ${{ steps.rename.outputs.apk_path }}

runs:
  using: "composite"
  steps:
    - name: "Flutter: Build APK"
      shell: bash
      run: |
        melos exec -c 1 --scope="fitness_tracker_application" -- \
          "flutter build apk --${{ inputs.mode }} --flavor ${{ inputs.flavor }} --target ${{ inputs.target }}"

    - name: "File: Rename APK"
      id: rename
      shell: bash
      run: |
        # Construct expected path based on standard Flutter output
        ORIGINAL_PATH="android/app/build/outputs/apk/${{ inputs.flavor }}/${{ inputs.mode }}/app-${{ inputs.flavor }}-${{ inputs.mode }}.apk"
        NEW_FILENAME="fitness-tracker-${{ inputs.flavor }}-${{ inputs.version-tag }}.apk"

        # Verify file exists
        if [ ! -f "$ORIGINAL_PATH" ]; then
          echo "❌ Error: APK not found at $ORIGINAL_PATH"
          exit 1
        fi

        mv "$ORIGINAL_PATH" "$NEW_FILENAME"
        echo "✅ Renamed APK to $NEW_FILENAME"

        echo "apk_path=$NEW_FILENAME" >> $GITHUB_OUTPUT
