name: "Flutter: Test"
description: "Runs tests, merges coverage, and uploads reports"
inputs:
  codecov-token:
    description: "Token for Codecov"
    required: false

runs:
  using: "composite"
  steps:
    - name: "OS: Install LCOV"
      shell: bash
      run: |
        if ! command -v lcov &> /dev/null; then
          sudo apt-get update -q && sudo apt-get install -y lcov
        fi

    - name: "Melos: Run Tests"
      shell: bash
      run: melos exec -c 6 --fail-fast -- "flutter test --coverage"

    - name: "LCOV: Merge Reports"
      id: merge_coverage
      shell: bash
      run: |
        mkdir -p coverage

        find . -type f -name "lcov.info" -not -path "./coverage/*" > lcov_files.txt

        if [ ! -s lcov_files.txt ]; then
          echo "⚠️ No lcov.info files found."
          echo "skipped=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Merging $(wc -l < lcov_files.txt) files..."
        cat lcov_files.txt | xargs lcov --add-file > coverage/lcov.raw.info

        lcov --remove coverage/lcov.raw.info \
          "*/test/*" "*/generated/*" "*/lib/*.g.dart" \
          "*/lib/*.freezed.dart" "*/lib/*.gr.dart" \
          "*/.dart_tool/*" \
          -o coverage/lcov.info --ignore-errors unused

        if [ ! -s coverage/lcov.info ]; then
           echo "⚠️ Coverage file is empty after filtering."
           echo "skipped=true" >> $GITHUB_OUTPUT
           exit 0
        fi

        echo "skipped=false" >> $GITHUB_OUTPUT

        genhtml coverage/lcov.info -o coverage/html \
          --ignore-errors source \
          --title "Flutter Coverage Report"

    - name: "Artifact: Upload Report"
      if: steps.merge_coverage.outputs.skipped != 'true'
      uses: actions/upload-artifact@v6
      with:
        name: flutter-coverage-html
        path: coverage/html
        retention-days: 7

    - name: "Codecov: Upload"
      uses: codecov/codecov-action@v5.5.2
      if: steps.merge_coverage.outputs.skipped != 'true'
      with:
        token: ${{ inputs.codecov-token }}
        files: coverage/lcov.info
        fail_ci_if_error: true
        verbose: true
