area/flutter:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.dart"
          - "pubspec.yaml"

area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "codecov.yml"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pubspec.yaml"
          - "pubspec.lock"
  - head-branch: ["^dependabot/"]

type/feature:
  - head-branch: ["^feature/", "^feat/"]

type/bug:
  - head-branch: ["^fix/", "^bugfix/", "^hotfix/"]

type/chore:
  - head-branch: ["^chore/", "^ci/"]
  - head-branch: ["^dependabot/"]

type/refactor:
  - head-branch: ["^refactor/"]

type/docs:
  - head-branch: ["^docs/"]
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "LICENSE"]

type/test:
  - head-branch: ["^test/", "^tests/"]
  - changed-files:
      - any-glob-to-any-file: ["test/**", "integration_test/**"]
